---
    name: Checks

    on:
      push:
        branches: ['**', '!main']


    permissions:
      actions: read
      attestations: read
      checks: read
      contents: read
      deployments: read
      id-token: none
      issues: read
      discussions: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read

    jobs:
      checkov:
        name: IaC security scan
        needs: []
        uses: fengz-org/gitops/.github/workflows/checkov.yml@main
        with:
          FAIL_ON_SECURITY_ISSUES: 'true'
          FRAMEWORK: 'terraform'
