---
    name: Checks

    on:
      push:
        branches: [main]


    permissions:
      actions: read
      attestations: read
      checks: read
      contents: read
      deployments: read
      id-token: none
      issues: read
      discussions: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read

    jobs:
      test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: testing
          run: |
            echo "The pipeline is working!"
      checkov:
        name: IaC security scan
        needs: [test]
        uses: fengzhu59/gitops-practice/.github/workflows/checkov.yml@main
        with:
          FAIL_ON_SECURITY_ISSUES: 'true'
          FRAMEWORK: 'terraform'
        # secrets:
        #   CHECKOV_CONFIG_CLONE_APP_ID: ${{ secrets.SEMANTIC_RELEASE_BOT_APP_ID }}
        #   CHECKOV_CONFIG_CLONE_PRIVATE_KEY: ${{ secrets.SEMANTIC_RELEASE_BOT_PRIVATE_KEY }}
