---
    name: Checks

    on:
      push:
        branches: [main]


    permissions:
      actions: write
      attestations: read
      checks: write
      contents: write
      deployments: read
      id-token: none
      issues: write
      discussions: read
      packages: read
      pages: read
      pull-requests: write
      repository-projects: read
      security-events: read
      statuses: write

    jobs:
      test:
        runs-on: ubuntu-latest

        steps:
        - name: testing
          run: |
            echo "The pipeline is working!"
      checkov:
        name: IaC security scan
        needs: [test]
        uses: fengz-org/gitops/.github/workflows/checkov.yml@main
        with:
          FAIL_ON_SECURITY_ISSUES: 'true'
          FRAMEWORK: 'terraform'
