---
    name: Danger checks
      
    on:
      workflow_call:
        inputs:
          runs-on:
            required: false
            type: string
            default: 'ubuntu-latest'
          container-image:
            required: false
            type: string
            default: 'registry.gitlab.com/gitlab-org/gitlab-build-images:danger'
            
    permissions:
      issues: write
      pull-requests: write 

    jobs:
      danger-checks:
        runs-on: ${{ inputs.runs-on }}
        container: ${{ inputs.container-image }}
        steps:
          - uses: actions/checkout@v4
          - run: |
              ls -la
              git config --global --add safe.directory '*'
              danger --fail-on-errors=true
            env:
              DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}