---
    name: Pull Request validation
    on:
      pull_request:
        branches: [main]
      workflow_dispatch:


    permissions:
        actions: write
        checks: write
        contents: write
        deployments: read
        id-token: write
        issues: write
        discussions: read
        packages: read
        pages: read
        pull-requests: write
        repository-projects: read
        security-events: read
        statuses: write

    jobs:
      danger_check:
        name: Danger Check
        uses: fengz-org/gitops/.github/workflows/danger-check.yml@main
