---
    name: Pull Request validation
    on:
      pull_request:
        branches: [main]
      workflow_dispatch:


    permissions:
        issues: write
        pull-requests: read

    jobs:
      danger_check:
        name: Danger Check
        uses: fengz-org/gitops/.github/workflows/danger-check.yml@main
