---
    name: Pull Request validation
    on:
      pull_request:
        branches: [main]
      workflow_dispatch:


    permissions:
        actions: read
        checks: read
        contents: read
        deployments: read
        id-token: none
        issues: read
        discussions: read
        packages: read
        pages: read
        pull-requests: read
        repository-projects: read
        security-events: read
        statuses: read

    jobs:
      danger_check:
        name: Danger Check
        uses: fengz-org/gitops/.github/workflows/danger-check.yml@main
