---
    name: release

    on:
        workflow_dispatch:
        push:
            branches:
            - main

    permissions:
        contents: write  #to be able to publish a GitHub release
        issues: write  #to be able to comment on released issues
        pull-requests: write  #to be able to comment on released pull requests
    

    jobs:
      release:
        name: semantic release
        needs: []
        uses: fengz-org/gitops/.github/workflows/semantic-release.yml@main
