---
    name: Terraform Plan

    permissions:
      actions: write
      checks: write
      contents: write
      deployments: read
      id-token: write
      issues: write
      discussions: read
      packages: read
      pages: read
      pull-requests: write
      repository-projects: read
      security-events: read
      statuses: write

    on:
      workflow_call:
        inputs:
          src_directory:
            required: true
            type: string
          terraform-version:
            required: false
            type: string
            default: 'latest'
          aws-region:
            required: false
            type: string
            default: 'eu-west-2'
          init-cmd:
            required: false
            type: string
          create-netrc:
            required: false
            default: 'false'
            type: string
          download-artifact:
            required: false
            type: string
            default: ''
          setup-cmd:
            required: false
            type: string
            default: ''

        secrets:
          AWS_ROLE_ARN:
            required: true
          PAT_SECRET:
            required: false
          GH_USER:
            required: false
          TF_VAR_GITHUB_ORGANIZATION:
            required: true
          TF_VAR_GITHUB_APP_ID:
            required: true
          TF_VAR_GITHUB_APP_INSTALLATION_ID:
            required: true
          TF_VAR_GITHUB_APP_PEM_FILE:
             required: true

    jobs:
      plan:
        runs-on: ubuntu-latest
        permissions:
          id-token: write
          contents: read

        env:
          app_id: ${{ secrets.TF_VAR_GITHUB_APP_ID }}
          installation_id: ${{ secrets.TF_VAR_GITHUB_APP_INSTALLATION_ID }}
          private_key: ${{ secrets.TF_VAR_GITHUB_APP_PEM_FILE }}

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Generate GitHub App Token
          id: generate_token
          uses: tibdex/github-app-token@v2
          with:
            app_id: ${{ secrets.TF_VAR_GITHUB_APP_ID }}
            installation_id: ${{ secrets.TF_VAR_GITHUB_APP_INSTALLATION_ID }}
            private_key: ${{ secrets.TF_VAR_GITHUB_APP_PEM_FILE }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: ${{ inputs.terraform-version }}

        - name: Terraform Format
          run: terraform fmt -check

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: ${{ inputs.aws-region }}

        - name: Create netrc file
          if: ${{ inputs.create-netrc == 'true' }}
          run: |
            echo "machine github.com
            login ${{ secrets.GH_USER }}
            password ${{ secrets.PAT_SECRET }}" > ~/.netrc

            chmod 600 ~/.netrc
          continue-on-error: false

        - name: Download Artifact
          if: ${{ inputs.download-artifact != '' }}
          uses: actions/download-artifact@v4
          with:
            name: ${{ inputs.download-artifact }}

        - name: Run Setup Command
          if: ${{ inputs.setup-cmd != '' }}
          run: ${{ inputs.setup-cmd }}

        - name: Terraform Init
          run: terraform init ${{ inputs.init-cmd }}
          working-directory: ${{ inputs.src_directory }}

        - name: Terraform Plan
          run: |
            echo "${{ secrets.TF_VAR_GITHUB_APP_PEM_FILE }}" > ./file.pem
            terraform plan -out=tfplan
            terraform show -no-color tfplan > tfplan.txt
            exit $exitcode
          env:
            TF_VAR_github_token: ${{ steps.generate_token.outputs.token }}
          continue-on-error: false

        - name: Upload Terraform Plan
          uses: actions/upload-artifact@v4
          with:
            name: tfplan
            path: tfplan
            retention-days: 5

        - name: Upload Plan Summary
          uses: actions/upload-artifact@v4
          with:
            name: tfplan-summary
            path: tfplan.txt
            retention-days: 5

        - name: Upload Terraform Plan to Job Summary
          if: always() # Always run to upload plan
          run: |
            echo '### Terraform Plan' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat tfplan.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY

        - name: Update Pull Request
          uses: actions/github-script@v7
          if: github.event_name == 'pull_request'
          env:
            PLAN: ${{ steps.plan.outputs.stdout }}
          with:
            github-token: ${{ steps.generate_token.outputs.token }}
            script: |
              const fs = require('fs');
              const planOutput = fs.readFileSync('tfplan.txt', 'utf8');

              // Truncate if plan is too long for GitHub comment
                const maxLength = 65000;
                const truncatedPlan = planOutput.length > maxLength
                  ? planOutput.substring(0, maxLength) + '\n\n... Plan truncated ...'
                  : planOutput;

              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## Terraform Plan Output\n\n\`\`\`\n${truncatedPlan}\n\`\`\``
              })

        - name: Clean up
          run: rm tfplan.txt
